#define CODE_SIZE 8192
#define DATA_SIZE 8192
#define STACK_SIZE 32
#define RSTACK_SIZE 16
#define SCREEN_W 640
#define SCREEN_H 480
#define KEY_NUM 16
#define RECT_NUM 64
#define RECT_SIZE 6
#define KEY_MEM 7792
#define KEY_UP 0
#define KEY_DOWN 1
#define KEY_LEFT 2
#define KEY_RIGHT 3
#define KEY_A 4
#define KEY_B 5
#define KEY_UP2 6
#define KEY_DOWN2 7
#define KEY_LEFT2 8
#define KEY_RIGHT2 9
#define KEY_A2 10
#define KEY_B2 11
#define RECT_MEM 7808
#define RECT_ABS 0
#define RECT_X 1
#define RECT_Y 2
#define RECT_W 3
#define RECT_H 4
#define RECT_COLOR 5
#define F1_IMM_POS 0
#define F1_IMM_SIZE 13
#define F1_OP_POS 13
#define F1_OP_SIZE 2
#define F1_F_POS 15
#define F1_F_SIZE 1
#define F2_SIMM_POS 0
#define F2_SIMM_SIZE 9
#define F2_I_POS 9
#define F2_I_SIZE 1
#define F2_OP_POS 10
#define F2_OP_SIZE 5
#define F2_F_POS 15
#define F2_F_SIZE 1
#define OP_JMP 0
#define OP_JZ 1
#define OP_CALL 2
#define OP_PUSH_ADDR 3
#define OP_ADD 0
#define OP_SUB 1
#define OP_MUL 2
#define OP_AND 3
#define OP_OR 4
#define OP_XOR 5
#define OP_SHL 6
#define OP_SHR 7
#define OP_SHRA 8
#define OP_EQ 9
#define OP_NEQ 10
#define OP_LT 11
#define OP_LE 12
#define OP_GT 13
#define OP_GE 14
#define OP_LTU 15
#define OP_LOAD 16
#define OP_STORE 17
#define OP_LOCALS 18
#define OP_SET_FP 19
#define OP_RET 20
#define OP_PUSH_INT 21
#define OP_PUSH_MR 22
#define OP_WAIT 23
